# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[profile.default]
solc_version = '0.6.0'
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
fuzz_runs = 1_000
remappings = [
  "forge-std=lib/forge-std/src/",
  "solmate=lib/solmate/src/",
  "@openzeppelin=lib/openzeppelin-contracts/contracts/"
]

rpc_endpoints = { mainnet = "${RPC_MAINNET}" }

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
